version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/musicdb
    depends_on:
      - mongo
    container_name: custom-app-name # Renaming the app container

  mongo:
    image: mongo:6.0
    container_name: custom-mongo-name # Renaming the mongo container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  jenkins_home:
